name: 'Synchronize readme.io documentation'
description: 'Synchronize a readme.io documentation from the readme of a Github repository'
inputs:
  document-slug:  
    description: 'Slug of the readme.io document to synchronize'
    required: true
  content:  
    description: 'The content of the document'
    required: true    
  readme-io-api-key:
    description: 'Your API key to request readme.io'
    required: true
  relative-links-host:  
    description: 'If provided, all relative markdown links in the document will be prefixed with this value'
    required: false        
outputs:
  response: # id of output
    description: 'The response status from readme.io'
runs:
  using: 'node12'
  main: 'index.js'