name: 'Synchronize readme.io documentation'
description: 'Synchronize a readme.io documentation from the readme of a Github repository'
inputs:
  document-slug:  
    description: 'Slug of the readme.io document to synchronize'
    required: true
  markdown-file-path:  
    description: 'The path of the markdown file to use for synchronization'
    required: true    
  readme-io-api-key:
    description: 'Your API key to request readme.io'
    required: true
  make-relative-links-absolute:  
    description: 'If true, all relative markdown links in the markdown will be made absolute'
    required: false        
    default: "false"
outputs:
  response: # id of output
    description: 'The response status from readme.io'
runs:
  using: 'node12'
  main: 'dist/index.js'